"""Reverse-state helpers for Innovation-2 local non-rigid alignment.

Training bootstraps originally used oracle physical states D~_t(X_GT) on the
HSI side.  Real inference instead sees states generated by the deterministic
reverse recursion.  This module exposes the exact global-identity inference
rollout and a differentiable local-flow pass over cached reverse states.

The Innovation-1 trajectory and reconstruction backbone are never modified by
these helpers.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple

import torch

from innovation1 import model_predict

SCALES = (4, 2, 1)


def _clear_alignment_state(model) -> None:
    if hasattr(model, "_training_local_cache"):
        model._training_local_cache = {}
    if hasattr(model, "_training_sequence_cache"):
        model._training_sequence_cache = {}
    if hasattr(model, "_reset_inference_local_state"):
        model._reset_inference_local_state()


def _set_global_identity_diagnostics(model, reference: torch.Tensor) -> None:
    model.last_global_shift_px = torch.zeros(
        reference.shape[0], 2, device=reference.device, dtype=reference.dtype
    )
    model.last_global_rotation_deg = torch.zeros(
        reference.shape[0], device=reference.device, dtype=reference.dtype
    )


@torch.no_grad()
def rollout_reverse_states_identity(
    model,
    process,
    gt: torch.Tensor,
    warped_msi: torch.Tensor,
) -> Dict[int, torch.Tensor]:
    """Cache the actual reverse states at the 4/2/1 representative timesteps.

    Global rigid correction is explicitly bypassed: ``warped_msi`` is passed
    directly to the predictor.  The model's normal inference local cache is
    allowed to update at physical scale transitions, so x_t follows the same
    state distribution that local-only validation sees.

    Returned tensors are detached HR-grid HSI states keyed by physical scale.
    """
    stage_t = {
        int(scale): int(model.geometry_aligner.stage_t_by_scale[int(scale)])
        for scale in SCALES
    }
    t_to_scale = {t: scale for scale, t in stage_t.items()}

    was_training = bool(model.training)
    model.eval()
    _clear_alignment_state(model)

    terminal_lr = process.terminal_observation(gt)
    x_t = process.terminal_state(
        terminal_lr,
        target_size=tuple(gt.shape[-2:]),
    )
    _set_global_identity_diagnostics(model, x_t)

    captured: Dict[int, torch.Tensor] = {}
    for t in range(int(process.total_steps), 0, -1):
        if t in t_to_scale:
            captured[int(t_to_scale[t])] = x_t.detach().clone()

        timestep = torch.full(
            (x_t.shape[0],),
            int(t),
            dtype=torch.long,
            device=x_t.device,
        )
        pred_x0 = model_predict(
            model,
            x_t,
            timestep,
            hr_msi=warped_msi,
        )
        x_t = process.reverse_update(x_t, pred_x0, int(t))

    missing = [scale for scale in SCALES if scale not in captured]
    if missing:
        raise RuntimeError(f"reverse rollout missed physical scales: {missing}")

    _clear_alignment_state(model)
    if was_training:
        model.train()
    return captured


def oracle_states(
    model,
    process,
    gt: torch.Tensor,
) -> Dict[int, torch.Tensor]:
    """Return the original training-time oracle physical states."""
    out: Dict[int, torch.Tensor] = {}
    for scale in SCALES:
        t_stage = int(model.geometry_aligner.stage_t_by_scale[scale])
        out[scale] = process.state_at(gt, t_stage)
    return out


def run_local_flow_from_states(
    model,
    states_by_scale: Dict[int, torch.Tensor],
    warped_msi: torch.Tensor,
) -> Tuple[Dict[int, torch.Tensor], Dict[int, List[torch.Tensor]]]:
    """Run differentiable recurrent 4->2->1 flow on supplied HSI states."""
    previous: Optional[torch.Tensor] = None
    final_by_scale: Dict[int, torch.Tensor] = {}
    sequence_by_scale: Dict[int, List[torch.Tensor]] = {}

    for scale in SCALES:
        if scale not in states_by_scale:
            raise KeyError(f"missing HSI state for physical scale {scale}")
        x_state = states_by_scale[scale]
        t_stage = int(model.geometry_aligner.stage_t_by_scale[scale])
        timesteps = torch.full(
            (x_state.shape[0],),
            t_stage,
            dtype=torch.long,
            device=x_state.device,
        )
        z_h, z_m = model.geometry_aligner.matched_states(
            x_state,
            warped_msi,
            timesteps,
        )
        dense, _, sequence = model.geometry_aligner.local_aligner(
            z_h,
            z_m,
            previous,
            scale=scale,
        )
        previous = dense
        final_by_scale[scale] = dense
        sequence_by_scale[scale] = sequence

    return final_by_scale, sequence_by_scale


def state_gap_metrics(
    oracle_by_scale: Dict[int, torch.Tensor],
    reverse_by_scale: Dict[int, torch.Tensor],
) -> Dict[int, Dict[str, float]]:
    """Simple HSI-state domain-gap diagnostics for each physical scale."""
    out: Dict[int, Dict[str, float]] = {}
    for scale in SCALES:
        oracle = oracle_by_scale[scale].detach().float()
        reverse = reverse_by_scale[scale].detach().float()
        diff = reverse - oracle
        out[scale] = {
            "mae": float(diff.abs().mean().item()),
            "rmse": float(torch.sqrt(diff.square().mean()).item()),
            "oracle_abs_mean": float(oracle.abs().mean().item()),
        }
    return out


__all__ = [
    "SCALES",
    "oracle_states",
    "rollout_reverse_states_identity",
    "run_local_flow_from_states",
    "state_gap_metrics",
]
