"""4->2->1 physical multiscale bootstrap for recurrent local non-rigid flow.

This is stage 2 after train_v4_local_bootstrap.py has proven that the recurrent
local updater can recover a synthetic local field at physical scale 1.

Protocol:
- local-only samples, 100%;
- learned global rigid alignment is bypassed (identity);
- recurrent local flow runs progressively at physical scales 4 -> 2 -> 1;
- scale-specific targets are generated by Innovation-1 itself:
    target_4 = D~_{t4}(target)
    target_2 = D~_{t2}(target)
    target_1 = target
  where t4/t2 are the representative timesteps used by the V4 aligner.
  Flow values remain in HR-pixel units; only spatial frequency/detail is
  reduced by the physical degradation/lift operator.
- no reconstruction/SAM/zero-response/smoothness losses are used.

The goal is to verify that the successful scale-1 recurrent estimator remains
stable when its residual flow is decomposed along the physical degradation
trajectory.
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F

from config import parse_args
from data_loader import build_loaders
from degradations.misalignment import make_misaligned_msi
from innovation1 import build_progressive_process
from main import _compact_float_tag
from train_v4_local_bootstrap import freeze_to_local_branch
from train_v4_recurrent_flow import build_recurrent_model, warm_start_compatible
from utils import AverageMeter, CSVLogger, count_parameters, ensure_dir, get_device, save_checkpoint, set_seed


SCALES = (4, 2, 1)


@dataclass
class MultiscaleBootstrapStats:
    loss: float
    final_epe_px: float
    final_true_mean_px: float
    final_pred_mean_px: float
    final_ratio: float
    scale4_epe_px: float
    scale2_epe_px: float
    scale1_epe_px: float
    scale4_target_mean_px: float
    scale2_target_mean_px: float
    scale1_target_mean_px: float
    scale4_pred_mean_px: float
    scale2_pred_mean_px: float
    scale1_pred_mean_px: float


def physical_flow_targets(
    process,
    stage_t_by_scale: Dict[int, int],
    target_flow: torch.Tensor,
) -> Dict[int, torch.Tensor]:
    """Build stage-specific displacement targets in HR-pixel units.

    Scale 4 and 2 use the exact Innovation-1 lifted degradation state, so only
    spatial detail/frequency is suppressed. Scale 1 keeps the full original
    target as the final objective.
    """
    if target_flow.ndim != 4 or target_flow.shape[1] != 2:
        raise ValueError("target_flow must have shape Bx2xHxW")
    targets: Dict[int, torch.Tensor] = {}
    for scale in SCALES:
        if scale == 1:
            targets[scale] = target_flow
            continue
        if scale not in stage_t_by_scale:
            raise KeyError(f"missing representative timestep for scale {scale}")
        t_stage = int(stage_t_by_scale[scale])
        targets[scale] = process.state_at(target_flow, t_stage)
    return targets


def stage_sequence_loss(
    sequence_by_scale: Dict[int, List[torch.Tensor]],
    targets_by_scale: Dict[int, torch.Tensor],
    *,
    normalization_px: float,
    gamma: float,
    stage_weights: Dict[int, float],
) -> torch.Tensor:
    """Discounted within-stage sequence loss + weighted 4/2/1 stage objectives."""
    norm = float(normalization_px)
    if norm <= 0.0:
        raise ValueError("normalization_px must be > 0")
    if not 0.0 < float(gamma) <= 1.0:
        raise ValueError("gamma must lie in (0,1]")

    total = None
    weight_total = 0.0
    for scale in SCALES:
        if scale not in sequence_by_scale or not sequence_by_scale[scale]:
            raise ValueError(f"missing recurrent predictions for scale {scale}")
        if scale not in targets_by_scale:
            raise ValueError(f"missing flow target for scale {scale}")
        stage_weight = float(stage_weights[scale])
        if stage_weight <= 0.0:
            raise ValueError("all stage weights must be > 0")

        sequence = sequence_by_scale[scale]
        stage_total = sequence[-1].new_zeros(())
        stage_weight_sum = 0.0
        n = len(sequence)
        target = targets_by_scale[scale]
        for index, pred in enumerate(sequence):
            iter_weight = float(gamma) ** float(n - index - 1)
            stage_total = stage_total + iter_weight * F.smooth_l1_loss(
                pred / norm,
                target / norm,
            )
            stage_weight_sum += iter_weight
        stage_total = stage_total / max(stage_weight_sum, 1e-12)
        total = stage_total * stage_weight if total is None else total + stage_weight * stage_total
        weight_total += stage_weight

    return total / max(weight_total, 1e-12)


def run_multiscale_sequence(
    model,
    process,
    gt: torch.Tensor,
    warped_msi: torch.Tensor,
) -> Tuple[Dict[int, torch.Tensor], Dict[int, List[torch.Tensor]]]:
    """Run local recurrent flow progressively at 4 -> 2 -> 1, global=identity."""
    previous: Optional[torch.Tensor] = None
    final_by_scale: Dict[int, torch.Tensor] = {}
    sequence_by_scale: Dict[int, List[torch.Tensor]] = {}

    for scale in SCALES:
        if scale not in model.geometry_aligner.stage_t_by_scale:
            raise KeyError(f"model has no physical stage for scale {scale}")
        t_stage = int(model.geometry_aligner.stage_t_by_scale[scale])
        x_stage = process.state_at(gt, t_stage)
        timesteps = torch.full(
            (gt.shape[0],),
            t_stage,
            dtype=torch.long,
            device=gt.device,
        )
        z_h, z_m = model.geometry_aligner.matched_states(
            x_stage,
            warped_msi,
            timesteps,
        )
        dense, _, sequence = model.geometry_aligner.local_aligner(
            z_h,
            z_m,
            previous,
            scale=scale,
        )
        previous = dense
        final_by_scale[scale] = dense
        sequence_by_scale[scale] = sequence

    return final_by_scale, sequence_by_scale


def field_metrics(pred: torch.Tensor, target: torch.Tensor) -> Tuple[float, float, float, float]:
    pred_f = pred.detach().float()
    target_f = target.detach().float()
    epe = torch.linalg.vector_norm(pred_f - target_f, dim=1).mean()
    pred_mag = torch.linalg.vector_norm(pred_f, dim=1).mean()
    target_mag = torch.linalg.vector_norm(target_f, dim=1).mean()
    ratio = pred_mag / target_mag.clamp_min(1e-8)
    return float(epe.item()), float(target_mag.item()), float(pred_mag.item()), float(ratio.item())


def train_epoch(
    model,
    loader,
    optimizer,
    process,
    device,
    *,
    local_max_px: float,
    control_grid: int,
    gamma: float,
    stage_weights: Dict[int, float],
    generator: Optional[torch.Generator],
) -> MultiscaleBootstrapStats:
    model.train()
    names = [
        "loss", "final_epe", "final_true", "final_pred", "final_ratio",
        "epe4", "epe2", "epe1",
        "true4", "true2", "true1",
        "pred4", "pred2", "pred1",
    ]
    meters = {name: AverageMeter() for name in names}

    for batch in loader:
        gt = batch["gt"].to(device, non_blocking=True)
        hr_msi = batch["hr_msi"].to(device, non_blocking=True)
        b = int(gt.shape[0])

        warped, _, params = make_misaligned_msi(
            hr_msi,
            translation_max_px=0.0,
            rotation_max_deg=0.0,
            local_max_displacement_px=float(local_max_px),
            control_grid_size=int(control_grid),
            generator=generator,
        )
        target_full = params.local_displacement_px
        targets = physical_flow_targets(
            process,
            model.geometry_aligner.stage_t_by_scale,
            target_full,
        )
        final_by_scale, sequences = run_multiscale_sequence(
            model,
            process,
            gt,
            warped,
        )
        loss = stage_sequence_loss(
            sequences,
            targets,
            normalization_px=float(local_max_px),
            gamma=float(gamma),
            stage_weights=stage_weights,
        )
        if not torch.isfinite(loss):
            raise FloatingPointError("non-finite multiscale bootstrap loss")

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(
            [p for p in model.parameters() if p.requires_grad],
            max_norm=1.0,
            error_if_nonfinite=True,
        )
        optimizer.step()

        epe1, true1, pred1, ratio1 = field_metrics(final_by_scale[1], targets[1])
        epe2, true2, pred2, _ = field_metrics(final_by_scale[2], targets[2])
        epe4, true4, pred4, _ = field_metrics(final_by_scale[4], targets[4])

        values = {
            "loss": float(loss.item()),
            "final_epe": epe1,
            "final_true": true1,
            "final_pred": pred1,
            "final_ratio": ratio1,
            "epe4": epe4,
            "epe2": epe2,
            "epe1": epe1,
            "true4": true4,
            "true2": true2,
            "true1": true1,
            "pred4": pred4,
            "pred2": pred2,
            "pred1": pred1,
        }
        for key, value in values.items():
            meters[key].update(value, b)

    return MultiscaleBootstrapStats(
        loss=meters["loss"].avg,
        final_epe_px=meters["final_epe"].avg,
        final_true_mean_px=meters["final_true"].avg,
        final_pred_mean_px=meters["final_pred"].avg,
        final_ratio=meters["final_ratio"].avg,
        scale4_epe_px=meters["epe4"].avg,
        scale2_epe_px=meters["epe2"].avg,
        scale1_epe_px=meters["epe1"].avg,
        scale4_target_mean_px=meters["true4"].avg,
        scale2_target_mean_px=meters["true2"].avg,
        scale1_target_mean_px=meters["true1"].avg,
        scale4_pred_mean_px=meters["pred4"].avg,
        scale2_pred_mean_px=meters["pred2"].avg,
        scale1_pred_mean_px=meters["pred1"].avg,
    )


@torch.no_grad()
def evaluate_severities(
    model,
    loader,
    process,
    device,
    *,
    severities: List[float],
    control_grid: int,
    trials: int,
    seed: int,
) -> Dict[float, Dict[str, float]]:
    model.eval()
    results: Dict[float, Dict[str, float]] = {}

    for local_max in severities:
        accum: Dict[str, List[float]] = {
            "final_epe": [], "final_true": [], "final_pred": [], "final_ratio": [],
            "epe4": [], "epe2": [], "epe1": [],
            "true4": [], "true2": [], "true1": [],
            "pred4": [], "pred2": [], "pred1": [],
        }
        for trial in range(int(trials)):
            generator = torch.Generator(device="cpu")
            generator.manual_seed(int(seed) + trial * 100003)

            for batch in loader:
                gt = batch["gt"].to(device, non_blocking=True)
                hr_msi = batch["hr_msi"].to(device, non_blocking=True)
                warped, _, params = make_misaligned_msi(
                    hr_msi,
                    translation_max_px=0.0,
                    rotation_max_deg=0.0,
                    local_max_displacement_px=float(local_max),
                    control_grid_size=int(control_grid),
                    generator=generator,
                )
                targets = physical_flow_targets(
                    process,
                    model.geometry_aligner.stage_t_by_scale,
                    params.local_displacement_px,
                )
                finals, _ = run_multiscale_sequence(model, process, gt, warped)

                e1, t1, p1, r1 = field_metrics(finals[1], targets[1])
                e2, t2, p2, _ = field_metrics(finals[2], targets[2])
                e4, t4, p4, _ = field_metrics(finals[4], targets[4])
                for key, value in {
                    "final_epe": e1, "final_true": t1, "final_pred": p1, "final_ratio": r1,
                    "epe4": e4, "epe2": e2, "epe1": e1,
                    "true4": t4, "true2": t2, "true1": t1,
                    "pred4": p4, "pred2": p2, "pred1": p1,
                }.items():
                    accum[key].append(float(value))

        results[float(local_max)] = {
            key: float(np.mean(values)) for key, values in accum.items()
        }

    return results


def parse_multiscale_args():
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--multiscale_init_checkpoint", type=str, required=True)
    parser.add_argument("--multiscale_local_max_px", type=float, default=1.0)
    parser.add_argument("--multiscale_control_grid", type=int, default=5)
    parser.add_argument("--multiscale_gamma", type=float, default=0.8)
    parser.add_argument("--multiscale_weight_scale4", type=float, default=0.5)
    parser.add_argument("--multiscale_weight_scale2", type=float, default=0.7)
    parser.add_argument("--multiscale_weight_scale1", type=float, default=1.0)
    parser.add_argument("--multiscale_iterations_scale4", type=int, default=3)
    parser.add_argument("--multiscale_iterations_scale2", type=int, default=2)
    parser.add_argument("--multiscale_iterations_scale1", type=int, default=2)
    parser.add_argument("--multiscale_max_update_scale4", type=float, default=2.0)
    parser.add_argument("--multiscale_max_update_scale2", type=float, default=1.0)
    parser.add_argument("--multiscale_max_update_scale1", type=float, default=0.5)
    parser.add_argument(
        "--multiscale_eval_severities",
        type=float,
        nargs="+",
        default=[0.5, 1.0, 2.0],
    )
    parser.add_argument("--multiscale_eval_trials", type=int, default=3)
    parser.add_argument("--multiscale_eval_interval", type=int, default=5)
    parser.add_argument("--multiscale_save_name", type=str, default="")
    args, remaining = parser.parse_known_args()
    cfg = parse_args(remaining)

    if cfg.stage != "train":
        raise ValueError("multiscale bootstrap is train-only; use --stage train")
    if str(cfg.predictor_version).lower() != "v4":
        raise ValueError("multiscale bootstrap requires --predictor_version v4")
    if args.multiscale_local_max_px <= 0.0:
        raise ValueError("--multiscale_local_max_px must be > 0")
    if args.multiscale_control_grid < 2:
        raise ValueError("--multiscale_control_grid must be >= 2")
    if not 0.0 < args.multiscale_gamma <= 1.0:
        raise ValueError("--multiscale_gamma must lie in (0,1]")
    if min(
        args.multiscale_weight_scale4,
        args.multiscale_weight_scale2,
        args.multiscale_weight_scale1,
    ) <= 0.0:
        raise ValueError("multiscale stage weights must be > 0")
    if min(
        args.multiscale_iterations_scale4,
        args.multiscale_iterations_scale2,
        args.multiscale_iterations_scale1,
    ) < 1:
        raise ValueError("multiscale iteration counts must be >= 1")
    if min(
        args.multiscale_max_update_scale4,
        args.multiscale_max_update_scale2,
        args.multiscale_max_update_scale1,
    ) <= 0.0:
        raise ValueError("multiscale max updates must be > 0")
    if args.multiscale_eval_trials < 1 or args.multiscale_eval_interval < 1:
        raise ValueError("multiscale eval counts must be >= 1")
    if any(v <= 0.0 for v in args.multiscale_eval_severities):
        raise ValueError("all multiscale eval severities must be > 0")

    cfg.recurrent_hidden_channels = 64
    cfg.recurrent_correlation_channels = 32
    cfg.recurrent_iterations_scale4 = int(args.multiscale_iterations_scale4)
    cfg.recurrent_iterations_scale2 = int(args.multiscale_iterations_scale2)
    cfg.recurrent_iterations_scale1 = int(args.multiscale_iterations_scale1)
    cfg.recurrent_max_update_scale4 = float(args.multiscale_max_update_scale4)
    cfg.recurrent_max_update_scale2 = float(args.multiscale_max_update_scale2)
    cfg.recurrent_max_update_scale1 = float(args.multiscale_max_update_scale1)
    return cfg, args


def output_paths(cfg, args):
    root = os.path.join(cfg.checkpoint_root, "innovation1")
    ensure_dir(root)
    if args.multiscale_save_name:
        stem = args.multiscale_save_name.removesuffix(".pth")
    else:
        stem = (
            f"{cfg.dataset}_v4_multiscale_bootstrap"
            f"_l{_compact_float_tag(args.multiscale_local_max_px)}"
            f"_it{args.multiscale_iterations_scale4}-"
            f"{args.multiscale_iterations_scale2}-"
            f"{args.multiscale_iterations_scale1}"
        )
    return (
        os.path.join(root, stem + ".pth"),
        os.path.join(root, stem + "_last.pth"),
        os.path.join(cfg.log_root, stem + ".csv"),
    )


def run(cfg, args):
    set_seed(cfg.seed)
    train_loader, test_loader, info = build_loaders(cfg)
    device = get_device(cfg.device)
    process = build_progressive_process(cfg)
    model = build_recurrent_model(cfg, info, device, process)

    source_epoch, source_best = warm_start_compatible(
        model,
        args.multiscale_init_checkpoint,
        device,
    )
    freeze_to_local_branch(model)

    stage_weights = {
        4: float(args.multiscale_weight_scale4),
        2: float(args.multiscale_weight_scale2),
        1: float(args.multiscale_weight_scale1),
    }
    print(
        "Physical multiscale bootstrap warm start: "
        f"{args.multiscale_init_checkpoint} "
        f"(epoch={source_epoch}, stored_best={source_best:.6f})"
    )
    print(
        "Protocol: local-only=100%, global=identity, scales=4->2->1, "
        "loss=stage-specific physical flow supervision only."
    )
    print(
        "Stage representatives: "
        + ", ".join(
            f"s{scale}:t{model.geometry_aligner.stage_t_by_scale[scale]}"
            for scale in SCALES
        )
    )
    print(
        f"weights s4/s2/s1={stage_weights[4]:g}/{stage_weights[2]:g}/{stage_weights[1]:g}, "
        f"iterations={cfg.recurrent_iterations_scale4}/"
        f"{cfg.recurrent_iterations_scale2}/"
        f"{cfg.recurrent_iterations_scale1}, "
        f"trainable={sum(p.numel() for p in model.parameters() if p.requires_grad)/1e6:.3f}M "
        f"/ total={count_parameters(model):.3f}M"
    )

    optimizer = torch.optim.Adam(
        [p for p in model.parameters() if p.requires_grad],
        lr=float(cfg.lr),
        weight_decay=float(cfg.weight_decay),
    )
    generator = torch.Generator(device="cpu")
    generator.manual_seed(
        int(cfg.seed) + int(getattr(cfg, "train_misalignment_seed_offset", 7919))
    )

    best_path, last_path, log_path = output_paths(cfg, args)
    logger = CSVLogger(
        log_path,
        fieldnames=[
            "epoch", "loss",
            "train_final_epe", "train_final_true", "train_final_pred", "train_final_ratio",
            "train_s4_epe", "train_s2_epe", "train_s1_epe",
            "train_s4_true", "train_s2_true", "train_s1_true",
            "train_s4_pred", "train_s2_pred", "train_s1_pred",
            "eval_l05_epe", "eval_l05_pred", "eval_l05_true",
            "eval_l1_epe", "eval_l1_pred", "eval_l1_true",
            "eval_l2_epe", "eval_l2_pred", "eval_l2_true",
            "best_eval_epe",
        ],
    )

    best_epe = float("inf")
    eval_seed = int(cfg.seed) + 15431
    for epoch in range(1, int(cfg.epochs) + 1):
        stats = train_epoch(
            model,
            train_loader,
            optimizer,
            process,
            device,
            local_max_px=float(args.multiscale_local_max_px),
            control_grid=int(args.multiscale_control_grid),
            gamma=float(args.multiscale_gamma),
            stage_weights=stage_weights,
            generator=generator,
        )
        print(
            f"Epoch {epoch:04d}/{cfg.epochs:04d} "
            f"loss={stats.loss:.6f} "
            f"s4 {stats.scale4_pred_mean_px:.3f}/{stats.scale4_target_mean_px:.3f} "
            f"s2 {stats.scale2_pred_mean_px:.3f}/{stats.scale2_target_mean_px:.3f} "
            f"s1 {stats.scale1_pred_mean_px:.3f}/{stats.scale1_target_mean_px:.3f} "
            f"final_ratio={stats.final_ratio:.3f} "
            f"final_EPE={stats.final_epe_px:.4f}"
        )

        eval_result = None
        if epoch % int(args.multiscale_eval_interval) == 0 or epoch == int(cfg.epochs):
            eval_result = evaluate_severities(
                model,
                test_loader,
                process,
                device,
                severities=[float(v) for v in args.multiscale_eval_severities],
                control_grid=int(args.multiscale_control_grid),
                trials=int(args.multiscale_eval_trials),
                seed=eval_seed,
            )
            for severity, result in eval_result.items():
                print(
                    f"  local<={severity:g}: "
                    f"s4={result['pred4']:.3f}/{result['true4']:.3f} "
                    f"s2={result['pred2']:.3f}/{result['true2']:.3f} "
                    f"s1={result['pred1']:.3f}/{result['true1']:.3f} "
                    f"EPE={result['final_epe']:.4f}"
                )

            reference = eval_result.get(float(args.multiscale_local_max_px))
            if reference is None:
                nearest = min(
                    eval_result,
                    key=lambda value: abs(value - float(args.multiscale_local_max_px)),
                )
                reference = eval_result[nearest]
            if float(reference["final_epe"]) < best_epe:
                best_epe = float(reference["final_epe"])
                save_checkpoint(
                    model,
                    optimizer,
                    epoch,
                    best_epe,
                    best_path,
                    extra={
                        "config": vars(cfg),
                        "multiscale_bootstrap": vars(args),
                        "evaluation": eval_result,
                    },
                )
                print(f"  saved best multiscale bootstrap -> {best_path}")

        row = {
            "epoch": epoch,
            "loss": stats.loss,
            "train_final_epe": stats.final_epe_px,
            "train_final_true": stats.final_true_mean_px,
            "train_final_pred": stats.final_pred_mean_px,
            "train_final_ratio": stats.final_ratio,
            "train_s4_epe": stats.scale4_epe_px,
            "train_s2_epe": stats.scale2_epe_px,
            "train_s1_epe": stats.scale1_epe_px,
            "train_s4_true": stats.scale4_target_mean_px,
            "train_s2_true": stats.scale2_target_mean_px,
            "train_s1_true": stats.scale1_target_mean_px,
            "train_s4_pred": stats.scale4_pred_mean_px,
            "train_s2_pred": stats.scale2_pred_mean_px,
            "train_s1_pred": stats.scale1_pred_mean_px,
            "best_eval_epe": best_epe,
        }
        if eval_result:
            for severity, tag in [(0.5, "05"), (1.0, "1"), (2.0, "2")]:
                if severity in eval_result:
                    row[f"eval_l{tag}_epe"] = eval_result[severity]["final_epe"]
                    row[f"eval_l{tag}_pred"] = eval_result[severity]["final_pred"]
                    row[f"eval_l{tag}_true"] = eval_result[severity]["final_true"]
        logger.write(row)

        if epoch % int(cfg.save_interval) == 0 or epoch == int(cfg.epochs):
            save_checkpoint(
                model,
                optimizer,
                epoch,
                best_epe,
                last_path,
                extra={
                    "config": vars(cfg),
                    "multiscale_bootstrap": vars(args),
                    "evaluation": eval_result,
                },
            )

    print("Physical multiscale bootstrap complete.")
    print(f"Best final scale-1 EPE: {best_epe:.6f}px")
    print(f"Best checkpoint: {best_path}")
    print(f"Last checkpoint: {last_path}")
    print(f"Log: {log_path}")


if __name__ == "__main__":
    cfg, args = parse_multiscale_args()
    run(cfg, args)
